### ISSUE TITLE
custom templates error

### ISSUE THREAD

**Issue by Stardustwings** [tomitrescak/meteor-uploads#90]
I follow the guide here (https://github.com/tomitrescak/meteor-uploads#custom-templates) to use custom templates,but I met the error "Uncaught TypeError: Cannot read property 'callbacks' of null". It seems that some data were missed. Is there something wrong with the guide about custom templates?

**Comment by tomitrescak** [comment]
Not really, can you post code of your custom template?

**Comment by Stardustwings** [comment]
@tomitrescak 

Here is my html


```html
<head>
  <title>upload-test</title>
</head>

<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}

  {{> customUpload}}
</body>

<template name="hello">
  <button>Click Me</button>
  <p>You've pressed the button {{counter}} times.</p>
</template>

<template name="customUpload">
    <form method="POST" enctype="multipart/form-data">
        <input type="file" class="jqUploadclass" data-form-data='{{ submitData }}'>
        {{#with infoLabel}}
            {{ infoLabel}} <button class="start">StartUpload</button>
            <div style="width: 200px; height: 30px; border: 1px solid black">
                <div style="background: red; height: 30px; width: {{ progress }}">
                    {{ progress }}
                </div>
            </div>
        {{/with}}

    </form>

    <!-- {{> upload_semanticUI }} -->
</template>

```

And here is my js

```javascript
if (Meteor.isClient) {
  // counter starts at 0
  Session.setDefault('counter', 0);

  Template.hello.helpers({
    counter: function () {
      return Session.get('counter');
    }
  });

  Template.hello.events({
    'click button': function () {
      // increment the counter when button is clicked
      Session.set('counter', Session.get('counter') + 1);
    }
  });

Template.customUpload.created = function() {
  Uploader.init(this);
}

Template.customUpload.rendered = function () {
  Uploader.render.call(this);
};

Template.customUpload.events({
  'click .start': function (e) {
    Uploader.startUpload.call(Template.instance(), e);
  }
});

Template.customUpload.helpers({
  'infoLabel': function() {
    var instance = Template.instance();

    // we may have not yet selected a file
    var info = instance.info.get()
    if (!info) {
      return;
    }

    var progress = instance.globalInfo.get();

    // we display different result when running or not
    return progress.running ?
      info.name + ' - ' + progress.progress + '% - [' + progress.bitrate + ']' :
      info.name + ' - ' + info.size + 'B';
  },
  'progress': function() {
    return Template.instance().globalInfo.get().progress + '%';
  }
})

}

if (Meteor.isServer) {
  Meteor.startup(function () {
    // code to run on server at startup

    UploadServer.init({
      tmpDir: process.env.PWD + '/.uploads/tmp',
      uploadDir: process.env.PWD + '/.uploads/',
      checkCreateDirectories: true //create the directories for you
    })
  });
}
```

Then when I click upload button, I get the error  "Uncaught TypeError: Cannot read property 'callbacks' of null" in uploader.js:186

**Comment by flamingm0e** [comment]
I have tried the example EXACTLY as provided in README.MD and I get the same error

**Comment by Habu-Kagumba** [comment]
Same here, followed the instructions and same error!!!!

**Comment by tomitrescak** [comment]
Sorry  for a very late answer. The problem has been fixed in the new release. There is nothing that needs to be done on your side. It should just start working. The problem was, that when template had no data context it would throw errors.

**Comment by Casear** [comment]
@tomitrescak  I got the same error. when will you publish next release? BTW ,Can I add callbacks  with custom template? if yes, how to do that ? thanks.

**Comment by tomitrescak** [comment]
Fix was posted ages ago. It should work now. Please check your code.

**Comment by Casear** [comment]
I use tomi:upload-jquery@2.1.7, but still get the same error.

**Comment by giggioz** [comment]
I think you just need to pass a data context to your custom template

`{{> customUpload callbacks=myCallbacks}}`

and then define `myCallbacks` in your helper.
